const mongoose = require("mongoose");

// Use PlayerSchema to create a new schema
const InfoSchema = new mongoose.Schema({
  hours: {
    type: Number,
    required: true,
    default: 0,
    max: 50,
  },
  percent: {
    type: Number,
    required: true,
    default: 0,
    max: 100,
  },
  sparq: {
    type: Number,
    default: 0,
  },
  comments: [
    {
      type: String,
    },
  ],
  OverallRating: { type: Number, trim: true },
  TraitDevelopment: { type: String, trim: true },
  OriginalHitPowerRating: { type: Number, trim: true },
  OriginalJumpingRating: { type: Number, trim: true },
  AgilityRating: { type: Number, trim: true },
  AccelerationRating: { type: Number, trim: true },
  OriginalKickAccuracyRating: { type: Number, trim: true },
  OriginalKickPowerRating: { type: Number, trim: true },
  BreakSackRating: { type: Number, trim: true },
  BlockSheddingRating: { type: Number, trim: true },
  BCVisionRating: { type: Number, trim: true },
  AwarenessRating: { type: Number, trim: true },
  CatchInTrafficRating: { type: Number, trim: true },
  CatchingRating: { type: Number, trim: true },
  CarryingRating: { type: Number, trim: true },
  BreakTackleRating: { type: Number, trim: true },
  DeepRouteRunningRating: { type: Number, trim: true },
  ChangeOfDirectionRating: { type: Number, trim: true },
  ImpactBlockingRating: { type: Number, trim: true },
  HitPowerRating: { type: Number, trim: true },
  FinesseMovesRating: { type: Number, trim: true },
  JukeMoveRating: { type: Number, trim: true },
  InjuryRating: { type: Number, trim: true },
  KickReturnRating: { type: Number, trim: true },
  KickPowerRating: { type: Number, trim: true },
  KickAccuracyRating: { type: Number, trim: true },
  JumpingRating: { type: Number, trim: true },
  MediumRouteRunningRating: { type: Number, trim: true },
  ManCoverageRating: { type: Number, trim: true },
  LongSnapRating: { type: Number, trim: true },
  LeadBlockRating: { type: Number, trim: true },
  PressRating: { type: Number, trim: true },
  PowerMovesRating: { type: Number, trim: true },
  RunBlockPowerRating: { type: Number, trim: true },
  RunBlockFinesseRating: { type: Number, trim: true },
  ReleaseRating: { type: Number, trim: true },
  PursuitRating: { type: Number, trim: true },
  SpeedRating: { type: Number, trim: true },
  SpectacularCatchRating: { type: Number, trim: true },
  ShortRouteRunningRating: { type: Number, trim: true },
  RunBlockRating: { type: Number, trim: true },
  StrengthRating: { type: Number, trim: true },
  StiffArmRating: { type: Number, trim: true },
  StaminaRating: { type: Number, trim: true },
  SpinMoveRating: { type: Number, trim: true },
  ThrowAccuracyRating: { type: Number, trim: true },
  ThrowAccuracyMidRating: { type: Number, trim: true },
  ThrowAccuracyDeepRating: { type: Number, trim: true },
  TackleRating: { type: Number, trim: true },
  ThrowUnderPressureRating: { type: Number, trim: true },
  ThrowPowerRating: { type: Number, trim: true },
  ThrowOnTheRunRating: { type: Number, trim: true },
  ThrowAccuracyShortRating: { type: Number, trim: true },
  ZoneCoverageRating: { type: Number, trim: true },
  TruckingRating: { type: Number, trim: true },
  ToughnessRating: { type: Number, trim: true },
  PlayActionRating: { type: Number, trim: true },
  PassBlockFinesseRating: { type: Number, trim: true },
  PassBlockPowerRating: { type: Number, trim: true },
  PassBlockRating: { type: Number, trim: true },
  Player: { type: String, trim: true },
  IsVisible: { type: String, trim: true },
  ProDayThreeConeDrill: { type: Number, trim: true },
  ProDayTwentyYardShuttle: { type: Number, trim: true },
  ProDayVerticalJump: { type: Number, trim: true },
  CombineTwentyYardShuttle: { type: Number, trim: true },
  CombineVerticalJump: { type: Number, trim: true },
  ProDayFortyYardDash: { type: Number, trim: true },
  CombineFortyYardDash: { type: Number, trim: true },
  CombineOverallGrade: { type: Number, trim: true },
  CombineThreeConeDrill: { type: Number, trim: true },
  ProDayBroadJump: { type: Number, trim: true },
  InitialDraftRank: { type: Number, trim: true },
  TrueOverallRanking: { type: Number, trim: true },
  CombineBenchPress: { type: Number, trim: true },
  ProDayBenchPress: { type: Number, trim: true },
  ProductionGrade: { type: Number, trim: true },
  CombineBroadJump: { type: Number, trim: true },
  stats: {
    type: Array,
    default: [],
  },
  bucket: { 
    type: mongoose.Schema.Types.ObjectId,
    ref: "Bucket"
  },
  player: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Player"
  },
  scout: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Scout"
  },
});

// Export the model
module.exports = mongoose.model("Info", InfoSchema);
