const mongoose = require("mongoose");
const slugify = require("slugify");

const PlayerSchema = new mongoose.Schema({
  FirstName: { type: String, trim: true },
  LastName: { type: String, trim: true },
  Position: { type: String, trim: true },
  Age: { type: String, trim: true },
  OverallRating: { type: String, trim: true },
  TraitDevelopment: { type: String, trim: true },
  ContractStatus: { type: String, trim: true },
  Motivation3: { type: String, trim: true },
  Motivation2: { type: String, trim: true },
  Motivation1: { type: String, trim: true },
  OriginalHitPowerRating: { type: String, trim: true },
  OriginalJumpingRating: { type: String, trim: true },
  AgilityRating: { type: String, trim: true },
  AccelerationRating: { type: String, trim: true },
  OriginalKickAccuracyRating: { type: String, trim: true },
  OriginalKickPowerRating: { type: String, trim: true },
  BreakSackRating: { type: String, trim: true },
  BlockSheddingRating: { type: String, trim: true },
  BCVisionRating: { type: String, trim: true },
  AwarenessRating: { type: String, trim: true },
  CatchInTrafficRating: { type: String, trim: true },
  CatchingRating: { type: String, trim: true },
  CarryingRating: { type: String, trim: true },
  BreakTackleRating: { type: String, trim: true },
  DeepRouteRunningRating: { type: String, trim: true },
  ConfidenceRating: { type: String, trim: true },
  ChangeOfDirectionRating: { type: String, trim: true },
  ImpactBlockingRating: { type: String, trim: true },
  HitPowerRating: { type: String, trim: true },
  Height: { type: String, trim: true },
  FinesseMovesRating: { type: String, trim: true },
  JukeMoveRating: { type: String, trim: true },
  InjuryRating: { type: String, trim: true },
  KickReturnRating: { type: String, trim: true },
  KickPowerRating: { type: String, trim: true },
  KickAccuracyRating: { type: String, trim: true },
  JumpingRating: { type: String, trim: true },
  MediumRouteRunningRating: { type: String, trim: true },
  ManCoverageRating: { type: String, trim: true },
  LongSnapRating: { type: String, trim: true },
  LeadBlockRating: { type: String, trim: true },
  PressRating: { type: String, trim: true },
  PowerMovesRating: { type: String, trim: true },
  RunBlockPowerRating: { type: String, trim: true },
  RunBlockFinesseRating: { type: String, trim: true },
  ReleaseRating: { type: String, trim: true },
  PursuitRating: { type: String, trim: true },
  SpeedRating: { type: String, trim: true },
  SpectacularCatchRating: { type: String, trim: true },
  ShortRouteRunningRating: { type: String, trim: true },
  RunBlockRating: { type: String, trim: true },
  StrengthRating: { type: String, trim: true },
  StiffArmRating: { type: String, trim: true },
  StaminaRating: { type: String, trim: true },
  SpinMoveRating: { type: String, trim: true },
  ThrowAccuracyRating: { type: String, trim: true },
  ThrowAccuracyMidRating: { type: String, trim: true },
  ThrowAccuracyDeepRating: { type: String, trim: true },
  TackleRating: { type: String, trim: true },
  ThrowUnderPressureRating: { type: String, trim: true },
  ThrowPowerRating: { type: String, trim: true },
  ThrowOnTheRunRating: { type: String, trim: true },
  ThrowAccuracyShortRating: { type: String, trim: true },
  ZoneCoverageRating: { type: String, trim: true },
  TruckingRating: { type: String, trim: true },
  ToughnessRating: { type: String, trim: true },
  PlayActionRating: { type: String, trim: true },
  PassBlockFinesseRating: { type: String, trim: true },
  PassBlockPowerRating: { type: String, trim: true },
  PassBlockRating: { type: String, trim: true },
  Player: { type: String, trim: true },
  IsVisible: { type: String, trim: true },
  ProDayThreeConeDrill: { type: String, trim: true },
  ProDayTwentyYardShuttle: { type: String, trim: true },
  ProDayVerticalJump: { type: String, trim: true },
  CombineTwentyYardShuttle: { type: String, trim: true },
  CombineVerticalJump: { type: String, trim: true },
  ProDayFortyYardDash: { type: String, trim: true },
  CombineFortyYardDash: { type: String, trim: true },
  CombineOverallGrade: { type: String, trim: true },
  CombineThreeConeDrill: { type: String, trim: true },
  ProDayBroadJump: { type: String, trim: true },
  InitialDraftRank: { type: String, trim: true },
  TrueOverallRanking: { type: String, trim: true },
  CombineBenchPress: { type: String, trim: true },
  ProDayBenchPress: { type: String, trim: true },
  ProductionGrade: { type: String, trim: true },
  CombineBroadJump: { type: String, trim: true },
  season: {
    type: mongoose.Schema.ObjectId,
    ref: "Season",
    required: true
  },
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'User',
    required: true
  },
  franchise: {
    type: mongoose.Schema.ObjectId,
    ref: 'Franchise',
    required: true
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model("Player", PlayerSchema);
